---
config:
  theme: redux-dark-color
---
sequenceDiagram

        actor UI
        participant Clinic
        participant Customer
        participant Member
        participant Coupon

        UI ->>+ Clinic : point_to_coupon(customer_id)

        loop
            Clinic ->>+ Customer : get_customer_info(customer_ID)
            Customer -->>- Clinic : return Customer
        end
        alt customer not found 
            Clinic -->> UI : return Customer not found
        end

        Clinic ->> Clinic : check_member(Customer)

        alt not member
            Clinic -->> UI : return Not member
        else is member
            Clinic ->>+ Member : get_tier()
            Member -->>- Clinic : return tier
            alt tier == silver 
                Clinic -->> UI : return silver tier cannot use coupon
            end

            Clinic ->>+ Member : (getter)point
            Member -->>- Clinic : return point

            alt point < 50
                Clinic -->> UI : return Not enough point
            end

            Clinic ->>+ Coupon : create_coupon()
            Coupon -->>- Clinic : return Coupon

            Clinic ->>+ Member : add_coupon(Coupon)
            Member -->>- Clinic : return Success

            Clinic ->>+ Member : remove_point(50)
            Member -->>- Clinic : return Success
            Clinic -->>- UI : return Success
        end