---
config:
  look: neo
  theme: redux-dark-color
---
sequenceDiagram
    actor Customer
    participant Clinic
    participant CustomerClass
    participant Pet
    participant Room
    participant PaymentMethod
    participant Reservation
    participant Notification
    autonumber
    
    Customer->>+Clinic: create_reservation(customer_id, pet_id, "Hotel", time, payment_method)
    
    loop search customer
        Clinic->>+CustomerClass: get_customer_info(customer_id)
        CustomerClass-->>-Clinic: return Customer
    end
    
    loop search pet
        Clinic ->>+ Pet: get_pet_info(pet_id)
        Pet -->>- Clinic: return Pet
    end
    
    Clinic->>PaymentMethod: create payment_obj (Card or QRCode)

    Clinic->>+Room: is_full
    Room-->>-Clinic: return False
    Clinic->>+Room: book_room()
    Room-->>-Clinic: return True
    Clinic->>+Room: get_price
    Room-->>-Clinic: return price

    alt payment is Card
        Clinic->>+PaymentMethod: pay(price, payment_method, customer, card_to_use)
        PaymentMethod-->>-Clinic: return "Success"
    else payment is QRCode
        Clinic->>+PaymentMethod: pay(price, payment_method)
        PaymentMethod-->>-Clinic: return "Success"
    end

    opt pay_result != "Success"
        Clinic->>Room: _is_full = False (Rollback)
        Clinic-->>Customer: return "Payment failed. Room reservation cancelled."
    end

    alt resource != None (มีห้องให้จองและจ่ายเงินผ่าน)
        Clinic->>Reservation: create HotelReservation()
        Clinic->>Clinic: __reservation.append(new_reservation)
        Clinic->>Customer: add_reservation(new_reservation)

        alt customer.email != None
            Clinic->>+Notification: send_confirmation("EMAIL", reservation_id)
            Notification-->>Clinic: return True
            Notification -->>- Customer: return Notification 
        else customer.phone != None
            Clinic->>+Notification: send_confirmation("SMS", reservation_id)
            Notification-->>Clinic: return True
            Notification -->>- Customer: return Notification
        end
        
        Clinic-->>Customer: return {"status": "success", ...}
    else resource == None (ห้องเต็ม)
        Clinic-->>-Customer: return {"status": "fail", ...}
    end