---
config:
  theme: redux-dark-color
---
sequenceDiagram

        actor UI
        participant Clinic
        participant Customer
        participant Member
        participant Payment
        participant PaymentMethod
        participant RewardsCard

        UI ->>+ Clinic : start_payment(customer_id,payment_type,money=None,card_ID=None,use_cp=False)
        Clinic ->> Clinic : start_calculate_total_price(customer_id,use_cp=False,use_rw_card=False)
        loop search_customer
            Clinic ->>+ Customer : get_customer_info(customer_id)
            Customer -->>- Clinic : return Customer
        end
        Clinic ->> Clinic : get_payment_method_object(customer,payment_type,card_ID)
        alt payment_type == qrcode
            Clinic ->>+ PaymentMethod : <<create>>(id)
            PaymentMethod -->>- Clinic : return QRCode(PaymentMethod)
        else payment_type == card
            loop search card
                Clinic ->>+ Customer : search_card(card_ID)
                Customer ->>+ PaymentMethod : getter(id)
                PaymentMethod -->>- Customer : return card_id
                alt correct card_id
                    Customer -->> Clinic : return Card(PaymentMethod)
                else 
                    Customer -->>- Clinic : return None
                end
            end
            alt Card == None
                Clinic -->> UI : return Invalid CardID
            end
        end
        %% Clinic ->>+ PaymentMethod : check_payment_type(payment_type)
        %% PaymentMethod -->>- Clinic : return PaymentMethod
        Clinic ->> Clinic : pay(price,PaymentMethod,money=None)  
        alt PaymentMethod == QRCode 
            Clinic ->>+ PaymentMethod : validate_money(money,price)
            PaymentMethod -->>- Clinic : return True / False
            alt False
                Clinic -->> UI : Invalid money
            end
        else PaymentMethod == Card
            Clinic ->>+ PaymentMethod : validate_money(money=None,price)
            PaymentMethod -->>- Clinic : return enough/not enough
            alt not enough
                Clinic -->> UI : Card not have enough money
            end
            Clinic ->>+ PaymentMethod : total_card_money(getter)
            PaymentMethod -->>- Clinic : return total_card_money
            Clinic ->>+ PaymentMethod : total_card_money(total_card_money - price)(setter)
            PaymentMethod -->>- Clinic : return success
        end
        Clinic ->>+ Member : check_member(customer)
        Member -->>- Clinic : return result(True/False)
        alt is member(True)
            Clinic ->>+ Member : calculate_point(price)
            Member ->> Member : add_point()
            Member -->>- Clinic : return point
            Clinic ->>+ Member : get_tier()
            Member -->>- Clinic : return tier
            alt tier = platinum
                Clinic ->>+ Member : add_count_to_rewards_card() 
                alt rewards_card = None
                    Member ->>+ RewardsCard : <<create>>
                    RewardsCard -->>- Member : return rewards_card(Instance)
                    Member ->> Member : add_rewards_card(rewards_card)
                else
                    Member ->>+ RewardsCard : add_count() 
                    RewardsCard -->>- Member : return Success
                end
                Member -->>- Clinic : return Success
            else tier = silver
                Clinic ->>+ Member : add_count_for_use_discount()
                Member -->>- Clinic :return success
            end
        end
        Clinic ->> Clinic : get_today()
        %% Service -->>- Clinic : return point
        Clinic ->>+ Payment : create_payment(customer_id,method,total_price,list_pet_and_service,today,point)
        Payment -->>- Clinic : return Payment
        Clinic ->>+ Customer : append Payment
        Customer -->>- Clinic : return success
        Clinic ->>+ Payment : create_payment_slip()
        Payment -->>- Clinic : return payment_slip
        Clinic -->>- UI : return payment_slip