---
config:
  theme: redux-dark-color
---
sequenceDiagram

        actor UI
        participant Clinic
        participant Service
        participant Customer
        participant Member
        participant Pet
        participant Payment
        participant Coupon
        participant PaymentMethod

        UI ->>+ Clinic : start_payment(customer_id,payment_type,money=None,card_ID=None,use_cp=False)
        loop search_customer
            Clinic ->>+ Customer : get_customer_info(customer_id)
            Customer -->>- Clinic : return Customer
        end
        alt customer not found 
            Clinic -->> UI : return Customer not found
        end
        Clinic ->>+ Customer : pet(getter)
        Customer -->>- Clinic : return pet_list

        loop each pet in pet_list
            loop search service in pet
                Clinic ->>+ Pet : search_unpaid_service()
                Pet -->>- Clinic : return service 
            end
            alt service is not None
                Clinic ->> Clinic : append in service_list
            end
        end
        loop for service in service_list
            Clinic ->>+ Service : sum_price_in_each_service(service_list)
            Service -->>- Clinic : return sum_price
        end
        Clinic ->> Clinic : calculate_total_price(customer,sum_price,use_cp=None)
        Clinic ->>+ Member : check_member(customer)
        Member -->>- Clinic : return result(True/False)
        alt is member(False)
            alt use_cp = True
                Clinic -->> UI : Not a member
            end
        else is member(True)
            Clinic ->> Clinic : calculate_discount(customer_id,sum_price)
            alt use_cp = True
                Clinic ->>+ Member : get_coupon(customer)
                Member -->>- Clinic : return coupon
                alt coupon == None 
                    Clinic -->> UI : return not have coupon
                else coupon != None
                    Clinic ->>+ Coupon : use_coupon(customer)
                    Coupon -->>- Clinic : return discount
                end
            end
        end
        %% Service -->>- Clinic : return price
        Clinic ->> Clinic : get_payment_method_object(customer,payment_type,card_ID)
        alt payment_type == qrcode
            Clinic ->>+ PaymentMethod : <<create>>(id)
            PaymentMethod -->>- Clinic : return QRCode(PaymentMethod)
        else payment_type == card
            loop search card
                Clinic ->>+ Customer : search_card(card_ID)
                Customer -->>- Clinic : return Card(PaymentMethod)
            end
            alt Card == None
                Clinic -->> UI : return Invalid CardID
            end
        end
        %% Clinic ->>+ PaymentMethod : check_payment_type(payment_type)
        %% PaymentMethod -->>- Clinic : return PaymentMethod
        Clinic ->> Clinic : pay(price,PaymentMethod,money=None)  
        alt PaymentMethod == QRCode 
            Clinic ->>+ PaymentMethod : validate_money(money,price)
            PaymentMethod -->>- Clinic : return True / False
            alt False
                Clinic -->> UI : Invalid money
            end
        else PaymentMethod == Card
            Clinic ->>+ PaymentMethod : validate_money(money=None,price)
            PaymentMethod -->>- Clinic : return enough/not enough
            alt not enough
                Clinic -->> UI : Card not have enough money
            end
            Clinic ->>+ PaymentMethod : total_card_money(getter)
            PaymentMethod -->>- Clinic : return total_card_money
            Clinic ->>+ PaymentMethod : total_card_money(total_card_money - 50)(setter)
            PaymentMethod -->>- Clinic : return success
        end
        alt is member(True)
            Clinic ->>+ Member : calculate_point(price)
            Member ->> Member : add_point()
            Member -->>- Clinic : return point
        end
        Clinic ->> Clinic : create_service_and_pet_list(pet_list,service_list)
        Clinic ->> Clinic : get_today()
        %% Service -->>- Clinic : return point
        Clinic ->>+ Payment : create_payment(customer_id,method,total_price,list_pet_and_service,today,point)
        Payment -->>- Clinic : return Payment
        Clinic ->>+ Customer : append Payment
        Customer -->>- Clinic : return success
        Clinic ->> Clinic : create_payment_slip()
        Clinic -->>- UI : return payment_slip