sequenceDiagram
    actor Employee
    participant Clinic
    participant Doctor
    participant Customer
    participant Pet
    participant Service
    participant MedicalService
    

    Employee ->>+ Clinic: medical_treatment(type, owner, doctor_id, pet, symptom, medicine, vaccine, price, doctor_obj)

    loop search doctor
        Clinic->>+Doctor: get_doctor_info(doctor_id)
        alt found
            Doctor-->>Clinic: return Doctor Object
        else not found
            Doctor-->>-Clinic: return doctor is not found
        end
    end

    %% Clinic ->>+ Doctor: start_medical_service(data, clinic_obj)

    loop search customer
        Clinic->>+Customer: get_customer_info(customer_id)
        alt found
            Customer-->>Clinic: return Customer Object
        else not found
            Customer-->>-Clinic: return customer is not found
        end
    end
    
    loop search pet
        Clinic->>+Customer: get_pet_info(pet_id)
        Customer ->>+ Pet : (getter) pet_id()
        Pet -->>- Customer : return pet_id
        alt found   
            Customer-->>Clinic: return Pet Object 
        else not found
            Customer-->>-Clinic: return pet is not found
        end
    end
    

    %% Doctor->>Doctor: update_information(symptom,medical,vaccine,price)
    
    %% Doctor->>Doctor: generate_record_id()
    Clinic->>+Doctor: create_medical_service(data, clinic_obj)

    Doctor->>+MedicalService: MedicalService(record_id,type,owner, doctor_id, pet, symptom, medicine, vaccine, price)    
    MedicalService-->>-Doctor: return MedicalService Object

    Doctor->>Doctor: append(medical_service)

    Doctor-->>-Clinic: return medical_service

    loop search last unpaid service 
        Clinic->>+Pet: search_unpaid_service()
        Pet-->>-Clinic: return unpaid_service
    end

    alt Found unpaid service
        Clinic->>+Service: append_sub_service(medical_service)
        Service-->>-Clinic: return add complete
    else Not found unpaid service
        Clinic->>+Service: Service(pet_id, customer_name, time)
        Service-->>-Clinic: return new_big_service

        Clinic->>+Service: append_sub_service(medical_service)
        Service-->>-Clinic: return add complete

        Clinic->>+Pet: append_big_service(new_big_service)
        Pet-->>-Clinic: return add complete
        
    end

    %% Doctor-->>-Clinic: return medical treatment complete

    Clinic-->>-Employee: return medical treatment complete

     