sequenceDiagram
    actor Doctor
    participant Clinic
    participant Customer
    participant Pet
    participant HotelService

    Doctor->>+Clinic: start_pet_admit(AdmitRequest)

    loop search pet
        Clinic->>+Customer: get_pet_info(pet_id)
        Customer ->>+ Pet : get_pet_info(pet_id)
        Pet -->>- Customer : return Pet Object
        Customer-->>-Clinic: return Pet Object 
    end

    loop search last unpaid service 
        Clinic->>+Pet: search_unpaid_service()
        Pet-->>-Clinic: return unpaid_service
    end

    Clinic ->>+ Service: check_has_mediacal_service()

    alt has_medical_service == None
        Service -->>- Clinic: return Admit is failed, No medical service
    end

    loop search private room
    Clinic->>+Room: get_type_room()
        Room-->>-Clinic: return type_room
        alt type_room == "privateroom"
            Clinic->>+Room: check_availability()
            Room->>+TimeSchedule: search_availability()
            TimeSchedule -->>- Room: return True
            Room-->>-Clinic: return True
            Clinic->>+Room: book_room(time_start, time_end)
            Room->>+TimeSchedule: update_schedule()
            TimeSchedule-->>-Room: return update complete
            Room -->>-Clinic: return Success
        end
    end

    alt resource != None
        Clinic->>+HotelService: create_hotel_service()
        HotelService -->>- Clinic: return hotel_service
        Clinic->>+Pet: append_sub_service(hotel_service)
        Pet-->>-Clinic: return add complete
        Clinic-->>Doctor: return status: success
    else resource == None
        Clinic-->>-Doctor: return status: fail, room not found
    end
    

    
    
   