---
config:
  look: neo
  theme: redux-dark-color
---
sequenceDiagram
autonumber
%% reservation
  actor Customer
  participant Clinic
  participant Pet
  participant Worker
  participant Room
  participant Doctor
  participant WorkSchedule
  participant Reservation
  participant Notification
Customer->>+Clinic: reservation(petID,type,time)
Clinic->>+Pet: getPetInfo(petID)
Pet-->>-Clinic: return petInfo (vaccine, aggressive)
alt มีให้จอง

alt อาบน้ำตัดขน
  Clinic->>Clinic: get_avaliable_worker()
Clinic ->>+ Worker: get_avaliable_work(time)
Worker ->>+ WorkSchedule: update_schedule(time)
WorkSchedule ->>- Worker: schedule_updated
Worker -->> Clinic: return true

end

alt จองห้องฝากเลี้ยง
  Clinic->>Clinic: get_avaliable_room()
Clinic ->>+ Room: is_full()
Room -->> Clinic: return False
end

alt นัดพบแพทย์
  Clinic->>Clinic: get_avaliable_doctor()
Clinic ->>+ Doctor: get_avaliable_work(time)
Doctor -->> Clinic: return true
Doctor ->>+ WorkSchedule: update_schedule(time)
WorkSchedule ->>- Doctor: schedule_updated

end
Clinic->>Clinic: calculateEstimatedPrice(pet, type)
Clinic ->>+ Reservation: create_reservation(customer, pet, service, price)
Reservation -->>- Clinic: return reservation_id
Clinic -->> Customer: reservation_created
alt มีSMS
Clinic->>+Notification: send_confirmation(SMS, reservation_id)
Notification -->> Customer: confirmation_sent
Notification-->>-Clinic: sent_success
else มีemail
Clinic->>+Notification: send_confirmation(email, reservation_id)
Notification -->> Customer: confirmation_sent
Notification-->>-Clinic: sent_success
end

else ไม่มีให้จอง
Worker -->>- Clinic: return Flase
Room -->>- Clinic: return True
Doctor   -->>- Clinic: return Flase
Clinic -->>- Customer: reservation_fail

end